# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Update GitHub Metrics

on:
  schedule: [{cron: "0 7 * * *"}]
  # Run workflow manually and on each commit to main branches
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Ensure xzcat exists for Nokogiri
      # - name: Install xz-utils and LZMA headers
        # run: |
          # sudo apt-get update
          # sudo apt-get install -y xz-utils liblzma-dev

      # 2) Remove redundant Google repo list to silence warnings
      # - name: Remove duplicate Google repo list
        # run: sudo rm -f /etc/apt/sources.list.d/google.list

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Output configuration
          filename: github-metrics.svg
          
          output_action: commit
          
          committer_branch: metrics-renders
          committer_message: "chore: update metrics [skip ci]"

          # Workflow cleanup
          clean_workflows: cancelled        # all, failure, success, startup_failure, timed_out, skipped
          optimize: css, xml, svg
          use_prebuilt_image: yes
          verify: yes
          debug_print: yes

          experimental_features: --optimize-svg
          
          # Error handling and retries
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          delay: 180
          
          user: chicago-joe
          template: classic
          
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          
          commits_authoring: chicago-joe,jloss94@gmail.com,connect@josephjloss.com
          config_order: |
            # "base.header",
            "introduction",
            "base.activity+community",
            "base.repositories",
            notable,
            lines,
            habits,
            repositories,
            wakatime,
            topics,
            traffic,
            music,
            stars,
            languages,
            isocalendar,
            activity,
            steam    
          config_display: regular
          config_octicon: yes
          # config_padding: 2, 8 + 11%
          config_padding: 10, 2 + 11%
          config_timezone: America/Chicago
          config_twemoji: yes
          
          config_output: auto    #svg png jpeg json markdown markdown-pdf
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: A
          
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 180
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 20
          plugin_habits_languages_threshold: 20%
          plugin_habits_trim: yes
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 30
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 3650
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 20%
          
          plugin_lines: yes
          plugin_lines_delay: 15
          plugin_lines_history_limit: 10
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base
          
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_mode: recent
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_time_range: long
          plugin_music_top_type: tracks
          plugin_music_user: bjl94
          
          plugin_notable: yes
          plugin_notable_from: user
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit
          
          plugin_pagespeed: no
          # plugin_pagespeed_url: https://josephjloss.com
          
          plugin_repositories: yes
          plugin_repositories_order: pinned, starred, random
          plugin_repositories_pinned: 10
          
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Screenshot
          plugin_screenshot_url: https://josephjloss.com
          # plugin_screenshot_viewport: '{"width": 1280, "height": 1280}'
          plugin_screenshot_wait: 500
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 365
          
          plugin_topics: yes
          plugin_topics_limit: 3
          plugin_topics_mode: icons
          plugin_topics_sort: starred
          plugin_traffic: yes

          # Plugins - Gaming & External
          plugin_steam: yes
          plugin_steam_achievements_limit: 3
          plugin_steam_games_limit: 2
          plugin_steam_playtime_threshold: 3
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: lossjj
          plugin_steam_token: ${{ secrets.STEAM_API_KEY }}
          
          # Plugins - Coding activity
          plugin_wakatime: yes
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 10
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: chicagojoe
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          
